-- MySQL Script generated by MySQL Workbench
-- Thu Nov 11 12:53:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pessoas_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pessoas_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pessoas_db` DEFAULT CHARACTER SET utf8 ;
USE `pessoas_db` ;

-- -----------------------------------------------------
-- Table `pessoas_db`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pessoas_db`.`Endereco` (
  `Id` INT NOT NULL,
  `Logradouro` VARCHAR(255) NOT NULL,
  `Numero` INT NOT NULL,
  `Cep` INT NOT NULL,
  `Bairro` VARCHAR(50) NOT NULL,
  `Cidade` VARCHAR(30) NOT NULL,
  `Estado` VARCHAR(20) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pessoas_db`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pessoas_db`.`Pessoa` (
  `Id` INT NOT NULL,
  `Nome` VARCHAR(256) NOT NULL,
  `Cpf` BIGINT(11) NOT NULL,
  `EnderecoId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Pessoa_Endereco_idx` (`EnderecoId` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_Endereco`
    FOREIGN KEY (`EnderecoId`)
    REFERENCES `pessoas_db`.`Endereco` (`Cidade`)
    ON DELETE CASCADE
    ON UPDATE NOT ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pessoas_db`.`Pessoa_Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pessoas_db`.`Pessoa_Telefone` (
  `Pessoa_Id` INT NOT NULL,
  `Telefone_Id` INT NOT NULL,
  INDEX `fk_Pessoa_Telefone_Pessoa1_idx` (`Pessoa_Id` ASC) VISIBLE,
  INDEX `fk_Pessoa_Telefone_Telefone1_idx` (`Telefone_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_Telefone_Pessoa1`
    FOREIGN KEY (`Pessoa_Id`)
    REFERENCES `pessoas_db`.`Pessoa` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NOT ACTION,
  CONSTRAINT `fk_Pessoa_Telefone_Telefone1`
    FOREIGN KEY (`Telefone_Id`)
    REFERENCES `pessoas_db`.`Telefone` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NOT ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pessoas_db`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pessoas_db`.`Telefone` (
  `Id` INT NOT NULL,
  `Numero` INT NOT NULL,
  `Ddd` INT NOT NULL,
  `TipoId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Telefone_Telefone_Tipo1_idx` (`TipoId` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_Telefone_Tipo1`
    FOREIGN KEY (`TipoId`)
    REFERENCES `pessoas_db`.`Telefone_Tipo` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NOT ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pessoas_db`.`Telefone_Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pessoas_db`.`Telefone_Tipo` (
  `Id` INT NOT NULL,
  `Tipo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
